// JavaScript Document

$(function() {
    $('#year.autocomplete').autocomplete({
        data: {
            "2016": null,
            "2015": null,
            "2017": null,
        }
    });
    $('#month.autocomplete').autocomplete({
        data: {
            "January": null,
            "February": null,
            "March": null,
            "April": null,
            "May": null,
            "June": null,
            "July": null,
            "August": null,
            "September": null,
            "October": null,
            "November": null,
            "December": null,
        }
    });
    $('#make.autocomplete').autocomplete({
        data: {
            "Ford": null,
            "Volkswagen": null,
            "BMW": null,
        }
    });
    $('#model.autocomplete').autocomplete({
        data: {
            "Model 1": null,
            "Model 2": null,
            "Model 3": null,
        }
    });
    $('#province.autocomplete').autocomplete({
        data: {
            "Gauteng": null,
            "Western Cape": null,
            "Eastern Cape": null,
            "Limpopo": null,
            "Mpumalanga": null,
        }
    });
    $('#dealerDetailsProvince.autocomplete').autocomplete({
        data: {
            "Gauteng": null,
            "Western Cape": null,
            "Eastern Cape": null,
            "Limpopo": null,
            "Mpumalanga": null,
        }
    });
    $('#dealerDetailsCity.autocomplete').autocomplete({
        data: {
            "Johannesburg": null,
            "Cape Town": null,
        }
    });
    $('#dealerDetailsSuburb.autocomplete').autocomplete({
        data: {
            "Northcliff": null,
            "Randburg": null,
            "Melville": null,
            "Rosebank": null,
            "Sandton": null,
            "Fourways": null,
            "Houghton Estate": null,
        }
    });
    $('#city.autocomplete').autocomplete({
        data: {
            "Johannesburg": null,
            "Cape Town": null,
        }
    });
    $('#suburb.autocomplete').autocomplete({
        data: {
            "Suburb 1": null,
            "Suburb 2": null,
        }
    });
    $('#financeApplicationPostalAddressSuburb.autocomplete').autocomplete({
        data: {
            "Northcliff": null,
            "Randburg": null,
            "Melville": null,
            "Rosebank": null,
            "Sandton": null,
            "Fourways": null,
            "Houghton Estate": null,
        }
    });
    $('#reviewApplicationSuburb.autocomplete').autocomplete({
        data: {
            "Northcliff": null,
            "Randburg": null,
            "Melville": null,
            "Rosebank": null,
            "Sandton": null,
            "Fourways": null,
            "Houghton Estate": null,
        }
    });
	$('#reviewApplicationPostalAddressSuburb.autocomplete').autocomplete({
        data: {
            "Northcliff": null,
            "Randburg": null,
            "Melville": null,
            "Rosebank": null,
            "Sandton": null,
            "Fourways": null,
            "Houghton Estate": null,
        }
    });
	$('#reviewApplicationIndustry.autocomplete').autocomplete({
        data: {
            "Manufacturing": null,
            "Finance": null,
            "Transport": null,
            "Contruction": null,
            "Steel": null,
            "Mining": null,
			"Retail": null,
			"Real Estate": null,
			"Textile": null,
        }
    });
	$('#reviewApplicationOccupation.autocomplete').autocomplete({
        data: {
            "Accountant": null,
            "Engineer": null,
            "Farmer": null,
            "Insurance Clerk": null,
            "Banker": null,
        }
    });
	$('#reviewApplicationBank.autocomplete').autocomplete({
        data: {
            "FNB": null,
            "Standard Bank": null,
            "Capitec": null,
            "Nedbank": null,
            "ABSA": null,
            "African Bank": null,
        }
    });
    $('#dealerName.autocomplete').autocomplete({
        data: {
            "Dealer 1": null,
            "Dealer 2": null,
        }
    });
    $('#reviewApplicationCountryOfBirth.autocomplete').autocomplete({
        data: {
            "Afghanistan": null,
            "Albania": null,
            "Algeria": null,
            "Andorra": null,
            "Angola": null,
            "Antigua & Deps": null,
            "Argentina": null,
            "Armenia": null,
            "Australia": null,
            "Austria": null,
            "Azerbaijan": null,
            "Bahamas": null,
            "Bahrain": null,
            "Bangladesh": null,
            "Barbados": null,
            "Belarus": null,
            "Belize": null,
            "Benin": null,
            "Bhutan": null,
            "Bolivia": null,
            "Bosnia Herzegovina": null,
            "Botswana": null,
            "Brazil": null,
            "Brunei": null,
            "Bulgaria": null,
            "Burkina": null,
            "Burundi": null,
            "Cambodia": null,
            "Cameroon": null,
            "Canada": null,
            "Cape Verde": null,
            "Central African Rep": null,
            "Chad": null,
            "Chile": null,
            "China": null,
            "Colombia": null,
            "Comoros": null,
            "Congo": null,
            "Congo {Democratic Rep}": null,
            "Costa Rica": null,
            "Croatia": null,
            "Cuba": null,
            "Cyprus": null,
            "Czech Republic": null,
            "Denmark": null,
            "Djibouti": null,
            "Dominica": null,
            "Dominican Republic": null,
            "East Timor": null,
            "Ecuador": null,
            "Egypt": null,
            "El Salvador": null,
            "Equatorial Guinea": null,
            "Eritrea": null,
            "Estonia": null,
            "Ethiopia": null,
            "Fiji": null,
            "Finland": null,
            "France": null,
            "Gabon": null,
            "Gambia": null,
            "Georgia": null,
            "Germany": null,
            "Ghana": null,
            "Greece": null,
            "Grenada": null,
            "Guatemala": null,
            "Guinea": null,
            "Guinea-Bissau": null,
            "Guyana": null,
            "Haiti": null,
            "Honduras": null,
            "Hungary": null,
            "Iceland": null,
            "India": null,
            "Indonesia": null,
            "Iran": null,
            "Iraq": null,
            "Ireland {Republic}": null,
            "Israel": null,
            "Italy": null,
            "Ivory Coast": null,
            "Jamaica": null,
            "Japan": null,
            "Jordan": null,
            "Kazakhstan": null,
            "Kenya": null,
            "Kiribati": null,
            "Korea North": null,
            "Korea South": null,
            "Kosovo": null,
            "Kuwait": null,
            "Kyrgyzstan": null,
            "Laos": null,
            "Latvia": null,
            "Lebanon": null,
            "Lesotho": null,
            "Liberia": null,
            "Libya": null,
            "Liechtenstein": null,
            "Lithuania": null,
            "Luxembourg": null,
            "Macedonia": null,
            "Madagascar": null,
            "Malawi": null,
            "Malaysia": null,
            "Maldives": null,
            "Mali": null,
            "Malta": null,
            "Marshall Islands": null,
            "Mauritania": null,
            "Mauritius": null,
            "Mexico": null,
            "Micronesia": null,
            "Moldova": null,
            "Monaco": null,
            "Mongolia": null,
            "Montenegro": null,
            "Morocco": null,
            "Mozambique": null,
            "Myanmar, {Burma}": null,
            "Namibia": null,
            "Nauru": null,
            "Nepal": null,
            "Netherlands": null,
            "New Zealand": null,
            "Nicaragua": null,
            "Niger": null,
            "Nigeria": null,
            "Norway": null,
            "Oman": null,
            "Pakistan": null,
            "Palau": null,
            "Panama": null,
            "Papua New Guinea": null,
            "Paraguay": null,
            "Peru": null,
            "Philippines": null,
            "Poland": null,
            "Portugal": null,
            "Qatar": null,
            "Romania": null,
            "Russian Federation": null,
            "Rwanda": null,
            "St Kitts & Nevis": null,
            "St Lucia": null,
            "Saint Vincent & the Grenadines": null,
            "Samoa": null,
            "San Marino": null,
            "Sao Tome & Principe": null,
            "Saudi Arabia": null,
            "Senegal": null,
            "Serbia": null,
            "Seychelles": null,
            "Sierra Leone": null,
            "Singapore": null,
            "Slovakia": null,
            "Slovenia": null,
            "Solomon Islands": null,
            "Somalia": null,
            "South Africa": null,
            "South Sudan": null,
            "Spain": null,
            "Sri Lanka": null,
            "Sudan": null,
            "Suriname": null,
            "Swaziland": null,
            "Sweden": null,
            "Switzerland": null,
            "Syria": null,
            "Taiwan": null,
            "Tajikistan": null,
            "Tanzania": null,
            "Thailand": null,
            "Togo": null,
            "Tonga": null,
            "Trinidad & Tobago": null,
            "Tunisia": null,
            "Turkey": null,
            "Turkmenistan": null,
            "Tuvalu": null,
            "Uganda": null,
            "Ukraine": null,
            "United Arab Emirates": null,
            "United Kingdom": null,
            "United States": null,
            "Uruguay": null,
            "Uzbekistan": null,
            "Vanuatu": null,
            "Vatican City": null,
            "Venezuela": null,
            "Vietnam": null,
            "Yemen": null,
            "Zambia": null,
            "Zimbabwe": null,
        }
    });
    $('#countryOfBirth.autocomplete').autocomplete({
        data: {
            "Afghanistan": null,
            "Albania": null,
            "Algeria": null,
            "Andorra": null,
            "Angola": null,
            "Antigua & Deps": null,
            "Argentina": null,
            "Armenia": null,
            "Australia": null,
            "Austria": null,
            "Azerbaijan": null,
            "Bahamas": null,
            "Bahrain": null,
            "Bangladesh": null,
            "Barbados": null,
            "Belarus": null,
            "Belize": null,
            "Benin": null,
            "Bhutan": null,
            "Bolivia": null,
            "Bosnia Herzegovina": null,
            "Botswana": null,
            "Brazil": null,
            "Brunei": null,
            "Bulgaria": null,
            "Burkina": null,
            "Burundi": null,
            "Cambodia": null,
            "Cameroon": null,
            "Canada": null,
            "Cape Verde": null,
            "Central African Rep": null,
            "Chad": null,
            "Chile": null,
            "China": null,
            "Colombia": null,
            "Comoros": null,
            "Congo": null,
            "Congo {Democratic Rep}": null,
            "Costa Rica": null,
            "Croatia": null,
            "Cuba": null,
            "Cyprus": null,
            "Czech Republic": null,
            "Denmark": null,
            "Djibouti": null,
            "Dominica": null,
            "Dominican Republic": null,
            "East Timor": null,
            "Ecuador": null,
            "Egypt": null,
            "El Salvador": null,
            "Equatorial Guinea": null,
            "Eritrea": null,
            "Estonia": null,
            "Ethiopia": null,
            "Fiji": null,
            "Finland": null,
            "France": null,
            "Gabon": null,
            "Gambia": null,
            "Georgia": null,
            "Germany": null,
            "Ghana": null,
            "Greece": null,
            "Grenada": null,
            "Guatemala": null,
            "Guinea": null,
            "Guinea-Bissau": null,
            "Guyana": null,
            "Haiti": null,
            "Honduras": null,
            "Hungary": null,
            "Iceland": null,
            "India": null,
            "Indonesia": null,
            "Iran": null,
            "Iraq": null,
            "Ireland {Republic}": null,
            "Israel": null,
            "Italy": null,
            "Ivory Coast": null,
            "Jamaica": null,
            "Japan": null,
            "Jordan": null,
            "Kazakhstan": null,
            "Kenya": null,
            "Kiribati": null,
            "Korea North": null,
            "Korea South": null,
            "Kosovo": null,
            "Kuwait": null,
            "Kyrgyzstan": null,
            "Laos": null,
            "Latvia": null,
            "Lebanon": null,
            "Lesotho": null,
            "Liberia": null,
            "Libya": null,
            "Liechtenstein": null,
            "Lithuania": null,
            "Luxembourg": null,
            "Macedonia": null,
            "Madagascar": null,
            "Malawi": null,
            "Malaysia": null,
            "Maldives": null,
            "Mali": null,
            "Malta": null,
            "Marshall Islands": null,
            "Mauritania": null,
            "Mauritius": null,
            "Mexico": null,
            "Micronesia": null,
            "Moldova": null,
            "Monaco": null,
            "Mongolia": null,
            "Montenegro": null,
            "Morocco": null,
            "Mozambique": null,
            "Myanmar, {Burma}": null,
            "Namibia": null,
            "Nauru": null,
            "Nepal": null,
            "Netherlands": null,
            "New Zealand": null,
            "Nicaragua": null,
            "Niger": null,
            "Nigeria": null,
            "Norway": null,
            "Oman": null,
            "Pakistan": null,
            "Palau": null,
            "Panama": null,
            "Papua New Guinea": null,
            "Paraguay": null,
            "Peru": null,
            "Philippines": null,
            "Poland": null,
            "Portugal": null,
            "Qatar": null,
            "Romania": null,
            "Russian Federation": null,
            "Rwanda": null,
            "St Kitts & Nevis": null,
            "St Lucia": null,
            "Saint Vincent & the Grenadines": null,
            "Samoa": null,
            "San Marino": null,
            "Sao Tome & Principe": null,
            "Saudi Arabia": null,
            "Senegal": null,
            "Serbia": null,
            "Seychelles": null,
            "Sierra Leone": null,
            "Singapore": null,
            "Slovakia": null,
            "Slovenia": null,
            "Solomon Islands": null,
            "Somalia": null,
            "South Africa": null,
            "South Sudan": null,
            "Spain": null,
            "Sri Lanka": null,
            "Sudan": null,
            "Suriname": null,
            "Swaziland": null,
            "Sweden": null,
            "Switzerland": null,
            "Syria": null,
            "Taiwan": null,
            "Tajikistan": null,
            "Tanzania": null,
            "Thailand": null,
            "Togo": null,
            "Tonga": null,
            "Trinidad & Tobago": null,
            "Tunisia": null,
            "Turkey": null,
            "Turkmenistan": null,
            "Tuvalu": null,
            "Uganda": null,
            "Ukraine": null,
            "United Arab Emirates": null,
            "United Kingdom": null,
            "United States": null,
            "Uruguay": null,
            "Uzbekistan": null,
            "Vanuatu": null,
            "Vatican City": null,
            "Venezuela": null,
            "Vietnam": null,
            "Yemen": null,
            "Zambia": null,
            "Zimbabwe": null,
        }
    });
    $('#reviewApplicationNationality.autocomplete').autocomplete({
        data: {
            "Afghan": null,
            "Albanian": null,
            "Algerian": null,
            "American": null,
            "Andorran": null,
            "Angolan": null,
            "Antiguans": null,
            "Argentinean": null,
            "Armenian": null,
            "Australian": null,
            "Austrian": null,
            "Azerbaijani": null,
            "Bahamian": null,
            "Bahraini": null,
            "Bangladeshi": null,
            "Barbadian": null,
            "Barbudans": null,
            "Batswana": null,
            "Belarusian": null,
            "Belgian": null,
            "Belizean": null,
            "Beninese": null,
            "Bhutanese": null,
            "Bolivian": null,
            "Bosnian": null,
            "Brazilian": null,
            "British": null,
            "Bruneian": null,
            "Bulgarian": null,
            "Burkinabe": null,
            "Burmese": null,
            "Burundian": null,
            "Cambodian": null,
            "Cameroonian": null,
            "Canadian": null,
            "Cape Verdean": null,
            "Central African": null,
            "Chadian": null,
            "Chilean": null,
            "Chinese": null,
            "Colombian": null,
            "Comoran": null,
            "Congolese": null,
            "Congolese": null,
            "Costa Rican": null,
            "Croatian": null,
            "Cuban": null,
            "Cypriot": null,
            "Czech": null,
            "Danish": null,
            "Djibouti": null,
            "Dominican": null,
            "Dominican": null,
            "Dutch": null,
            "Dutchman": null,
            "Dutchwoman": null,
            "East Timorese": null,
            "Ecuadorean": null,
            "Egyptian": null,
            "Emirian": null,
            "Equatorial Guinean": null,
            "Eritrean": null,
            "Estonian": null,
            "Ethiopian": null,
            "Fijian": null,
            "Filipino": null,
            "Finnish": null,
            "French": null,
            "Gabonese": null,
            "Gambian": null,
            "Georgian": null,
            "German": null,
            "Ghanaian": null,
            "Greek": null,
            "Grenadian": null,
            "Guatemalan": null,
            "Guinea - Bissauan": null,
            "Guinean": null,
            "Guyanese": null,
            "Haitian": null,
            "Herzegovinian": null,
            "Honduran": null,
            "Hungarian": null,
            "I - Kiribati": null,
            "Icelander": null,
            "Indian": null,
            "Indonesian": null,
            "Iranian": null,
            "Iraqi": null,
            "Irish": null,
            "Israeli": null,
            "Italian": null,
            "Ivorian": null,
            "Jamaican": null,
            "Japanese": null,
            "Jordanian": null,
            "Kazakhstani": null,
            "Kenyan": null,
            "Kittian and Nevisian": null,
            "Kuwaiti": null,
            "Kyrgyz": null,
            "Laotian": null,
            "Latvian": null,
            "Lebanese": null,
            "Liberian": null,
            "Libyan": null,
            "Liechtensteiner": null,
            "Lithuanian": null,
            "Luxembourger": null,
            "Macedonian": null,
            "Malagasy": null,
            "Malawian": null,
            "Malaysian": null,
            "Maldivan": null,
            "Malian": null,
            "Maltese": null,
            "Marshallese": null,
            "Mauritanian": null,
            "Mauritian": null,
            "Mexican": null,
            "Micronesian": null,
            "Moldovan": null,
            "Monacan": null,
            "Mongolian": null,
            "Moroccan": null,
            "Mosotho": null,
            "Motswana": null,
            "Mozambican": null,
            "Namibian": null,
            "Nauruan": null,
            "Nepalese": null,
            "Netherlander": null,
            "New Zealander": null,
            "Ni - Vanuatu": null,
            "Nicaraguan": null,
            "Nigerian": null,
            "Nigerien": null,
            "North Korean": null,
            "Northern Irish": null,
            "Norwegian": null,
            "Omani": null,
            "Pakistani": null,
            "Palauan": null,
            "Panamanian": null,
            "Papua New Guinean": null,
            "Paraguayan": null,
            "Peruvian": null,
            "Polish": null,
            "Portuguese": null,
            "Qatari": null,
            "Romanian": null,
            "Russian": null,
            "Rwandan": null,
            "Saint Lucian": null,
            "Salvadoran": null,
            "Samoan": null,
            "San Marinese": null,
            "Sao Tomean": null,
            "Saudi": null,
            "Scottish": null,
            "Senegalese": null,
            "Serbian": null,
            "Seychellois": null,
            "Sierra Leonean": null,
            "Singaporean": null,
            "Slovakian": null,
            "Slovenian": null,
            "Solomon Islander": null,
            "Somali": null,
            "South African": null,
            "South Korean": null,
            "Spanish": null,
            "Sri Lankan": null,
            "Sudanese": null,
            "Surinamer": null,
            "Swazi": null,
            "Swedish": null,
            "Swiss": null,
            "Syrian": null,
            "Taiwanese": null,
            "Tajik": null,
            "Tanzanian": null,
            "Thai": null,
            "Togolese": null,
            "Tongan": null,
            "Trinidadian or Tobagonian": null,
            "Tunisian": null,
            "Turkish": null,
            "Tuvaluan": null,
            "Ugandan": null,
            "Ukrainian": null,
            "Uruguayan": null,
            "Uzbekistani": null,
            "Venezuelan": null,
            "Vietnamese": null,
            "Welsh": null,
            "Yemenite": null,
            "Zambian": null,
            "Zimbabwean": null,
        }
    });
    $('#nationality.autocomplete').autocomplete({
        data: {
            "Afghan": null,
            "Albanian": null,
            "Algerian": null,
            "American": null,
            "Andorran": null,
            "Angolan": null,
            "Antiguans": null,
            "Argentinean": null,
            "Armenian": null,
            "Australian": null,
            "Austrian": null,
            "Azerbaijani": null,
            "Bahamian": null,
            "Bahraini": null,
            "Bangladeshi": null,
            "Barbadian": null,
            "Barbudans": null,
            "Batswana": null,
            "Belarusian": null,
            "Belgian": null,
            "Belizean": null,
            "Beninese": null,
            "Bhutanese": null,
            "Bolivian": null,
            "Bosnian": null,
            "Brazilian": null,
            "British": null,
            "Bruneian": null,
            "Bulgarian": null,
            "Burkinabe": null,
            "Burmese": null,
            "Burundian": null,
            "Cambodian": null,
            "Cameroonian": null,
            "Canadian": null,
            "Cape Verdean": null,
            "Central African": null,
            "Chadian": null,
            "Chilean": null,
            "Chinese": null,
            "Colombian": null,
            "Comoran": null,
            "Congolese": null,
            "Congolese": null,
            "Costa Rican": null,
            "Croatian": null,
            "Cuban": null,
            "Cypriot": null,
            "Czech": null,
            "Danish": null,
            "Djibouti": null,
            "Dominican": null,
            "Dominican": null,
            "Dutch": null,
            "Dutchman": null,
            "Dutchwoman": null,
            "East Timorese": null,
            "Ecuadorean": null,
            "Egyptian": null,
            "Emirian": null,
            "Equatorial Guinean": null,
            "Eritrean": null,
            "Estonian": null,
            "Ethiopian": null,
            "Fijian": null,
            "Filipino": null,
            "Finnish": null,
            "French": null,
            "Gabonese": null,
            "Gambian": null,
            "Georgian": null,
            "German": null,
            "Ghanaian": null,
            "Greek": null,
            "Grenadian": null,
            "Guatemalan": null,
            "Guinea - Bissauan": null,
            "Guinean": null,
            "Guyanese": null,
            "Haitian": null,
            "Herzegovinian": null,
            "Honduran": null,
            "Hungarian": null,
            "I - Kiribati": null,
            "Icelander": null,
            "Indian": null,
            "Indonesian": null,
            "Iranian": null,
            "Iraqi": null,
            "Irish": null,
            "Israeli": null,
            "Italian": null,
            "Ivorian": null,
            "Jamaican": null,
            "Japanese": null,
            "Jordanian": null,
            "Kazakhstani": null,
            "Kenyan": null,
            "Kittian and Nevisian": null,
            "Kuwaiti": null,
            "Kyrgyz": null,
            "Laotian": null,
            "Latvian": null,
            "Lebanese": null,
            "Liberian": null,
            "Libyan": null,
            "Liechtensteiner": null,
            "Lithuanian": null,
            "Luxembourger": null,
            "Macedonian": null,
            "Malagasy": null,
            "Malawian": null,
            "Malaysian": null,
            "Maldivan": null,
            "Malian": null,
            "Maltese": null,
            "Marshallese": null,
            "Mauritanian": null,
            "Mauritian": null,
            "Mexican": null,
            "Micronesian": null,
            "Moldovan": null,
            "Monacan": null,
            "Mongolian": null,
            "Moroccan": null,
            "Mosotho": null,
            "Motswana": null,
            "Mozambican": null,
            "Namibian": null,
            "Nauruan": null,
            "Nepalese": null,
            "Netherlander": null,
            "New Zealander": null,
            "Ni - Vanuatu": null,
            "Nicaraguan": null,
            "Nigerian": null,
            "Nigerien": null,
            "North Korean": null,
            "Northern Irish": null,
            "Norwegian": null,
            "Omani": null,
            "Pakistani": null,
            "Palauan": null,
            "Panamanian": null,
            "Papua New Guinean": null,
            "Paraguayan": null,
            "Peruvian": null,
            "Polish": null,
            "Portuguese": null,
            "Qatari": null,
            "Romanian": null,
            "Russian": null,
            "Rwandan": null,
            "Saint Lucian": null,
            "Salvadoran": null,
            "Samoan": null,
            "San Marinese": null,
            "Sao Tomean": null,
            "Saudi": null,
            "Scottish": null,
            "Senegalese": null,
            "Serbian": null,
            "Seychellois": null,
            "Sierra Leonean": null,
            "Singaporean": null,
            "Slovakian": null,
            "Slovenian": null,
            "Solomon Islander": null,
            "Somali": null,
            "South African": null,
            "South Korean": null,
            "Spanish": null,
            "Sri Lankan": null,
            "Sudanese": null,
            "Surinamer": null,
            "Swazi": null,
            "Swedish": null,
            "Swiss": null,
            "Syrian": null,
            "Taiwanese": null,
            "Tajik": null,
            "Tanzanian": null,
            "Thai": null,
            "Togolese": null,
            "Tongan": null,
            "Trinidadian or Tobagonian": null,
            "Tunisian": null,
            "Turkish": null,
            "Tuvaluan": null,
            "Ugandan": null,
            "Ukrainian": null,
            "Uruguayan": null,
            "Uzbekistani": null,
            "Venezuelan": null,
            "Vietnamese": null,
            "Welsh": null,
            "Yemenite": null,
            "Zambian": null,
            "Zimbabwean": null,
        }
    });
});
